### ISSUE TITLE
设置 输入框 后面的图片大小

### ISSUE THREAD

**Issue by Jetereting** [yinLiangDream/mp-colorui#11]
我想设置 输入框 后面的图片大小，我是这么做的：

![image](https://user-images.githubusercontent.com/11585188/65292370-bda1a280-db89-11e9-814f-4ffd89f20d60.png)

![image](https://user-images.githubusercontent.com/11585188/65292417-ed50aa80-db89-11e9-95e8-d2deb564826c.png)

![image](https://user-images.githubusercontent.com/11585188/65292423-f9d50300-db89-11e9-8aac-73824e449963.png)

但是它没有起效，我不知道是什么原因

**Comment by yinLiangDream** [comment]
加个 !important;
就是
```scss
max-width: 100px !important;
```

**Comment by Jetereting** [comment]
还是没有达到效果，我甚至试图把所有的 图片宽度都改变为特定值，但是效果没有任何变化

![image](https://user-images.githubusercontent.com/11585188/65319289-d2a22400-dbd1-11e9-9dc5-2f0c17e7d2dc.png)


是不是不支持按照标签写

**Comment by yinLiangDream** [comment]
@Jetereting 我看第一张图编译下来是 `100rpx`， 根据目前的情况来看，`100rpx` 和 `50px` 在 375 宽的屏幕上显示效果是一致的，我估计你是想要宽一点？试试 `max-width: 200px !important;`

**Comment by Jetereting** [comment]
感谢回复，还是没有生效
好像是我怎么写 他都没有效果

![image](https://user-images.githubusercontent.com/11585188/65323565-434e3e00-dbdc-11e9-9635-468b238e4f4a.png)

**Comment by yinLiangDream** [comment]
注意看你的是PX，而微信只支持rpx和px，是否是编译问题？你试试手动将PX改为rpx看看是否有效果

**Comment by Jetereting** [comment]
![image](https://user-images.githubusercontent.com/11585188/65324789-cb821280-dbdf-11e9-82d4-e8635cf2b97c.png)

它有毒😂

**Comment by yinLiangDream** [comment]
兄弟你是不是 image 写错了……，写成 imgae 了……

**Comment by Jetereting** [comment]
写错了😂，生效了，谢谢大佬
