### ISSUE TITLE
含有 Input  控件的页面会报 width 错误，有没有解决的方法

### ISSUE THREAD

**Issue by Jetereting** [yinLiangDream/mp-colorui#12]
![image](https://user-images.githubusercontent.com/11585188/65292606-a7481680-db8a-11e9-8cdd-fc207069dd62.png)

```tsx
      <View className='index'>
        <ClInput title='姓名' titleWidth={150} type='text' placeholder='超过3个字的，可只输入前3个' value={this.state.name} maxLength={15} onChange={this.nameChange.bind(this)} />
        <ClInput title='准考证号' titleWidth={150} type='number' placeholder={'15位笔试或口试准考证号'} value={this.state.numb} maxLength={15} onChange={this.numbChange.bind(this)} />
        <View className='LoginButton'>
          <ClButton loading={this.state.isLoading} long plain bgColor='gradualBlue' onClick={this.clickLogin.bind(this)}> 预存 </ClButton>
        </View>
      </View>
```

**Comment by yinLiangDream** [comment]
这个问题我下个版本会修复，同时 input 组件会新增一个 defaultValue 属性，区别于 value，具体可以看文档，目前预计更新时间为 23 号

**Comment by Jetereting** [comment]
大佬好棒

**Comment by yinLiangDream** [comment]
@Jetereting 新版本已修复这个问题，更新一下，有问题再提哈

**Comment by Jetereting** [comment]
@yinLiangDream  生效！谢谢大佬，弱弱问下，更新npm依赖 一般怎么更，我是手动删除了 node_modules 的 mp-colorui 文件夹，然后 再 npm i mp-colorui ，感觉会有比这优雅的方法

**Comment by yinLiangDream** [comment]
@Jetereting 
npm update name --save
name 是指定包名，我这边就写 mp-colorui

如果想及时查看依赖包的最新版本，使用 vscode 开发查找 Version Lens 插件
![image](https://user-images.githubusercontent.com/24502330/65390144-1c843900-dd8f-11e9-9390-8564efd603af.png)
他会自动获取包信息，提示你版本信息
![image](https://user-images.githubusercontent.com/24502330/65390180-62410180-dd8f-11e9-8996-29969cf9a736.png)
点一下，他会帮你改为最新版本，你自己再 npm install 一下就好

**Comment by Jetereting** [comment]
@yinLiangDream Get Thanks!
