### ISSUE TITLE
文档网站 预览会遮盖内容

### ISSUE THREAD

**Issue by Jetereting** [yinLiangDream/mp-colorui#13]
https://yinliangdream.github.io/mp-colorui-doc/#/form/input

![image](https://user-images.githubusercontent.com/11585188/65292769-3fde9680-db8b-11e9-9c3b-069dae8342d4.png)

建议添加个预览收起按钮；

chrome  浏览器在 Input 页面停留几分钟，该页面会崩溃
![image](https://user-images.githubusercontent.com/11585188/65292807-6a305400-db8b-11e9-9aab-c1512a0b5b44.png)

**Comment by yinLiangDream** [comment]
这个我待会就优化一下……

**Comment by yinLiangDream** [comment]
这个临时好了，清一下缓存重新打开就可以看到
![image](https://user-images.githubusercontent.com/24502330/65297507-b1721100-db9a-11e9-8d04-d3cb9fde3915.png)

**Comment by Jetereting** [comment]
大佬好棒
