### ISSUE TITLE
平台支持度

### ISSUE THREAD

**Issue by 100cm** [yinLiangDream/mp-colorui#14]
1.请问这个支持支付宝小程序吗？
2.有计划支持支付宝小程序吗

**Comment by yinLiangDream** [comment]
1、目前只有部分组件支持支付宝小程序，还是有些平台兼容性问题
2、目前已经在初步测试编译成支付宝小程序的组件，待修问题，预计 0.5.0 版本全面支持

**Comment by yinLiangDream** [comment]
0.5.0版本已发布
