### ISSUE TITLE
看 github 已经到 v0.5.0,但是npm 还是 v0.4.12

### ISSUE THREAD

**Issue by Jetereting** [yinLiangDream/mp-colorui#17]
看 github库版本 已经到 v0.5.0,但是npm 还是 v0.4.12

**Comment by yinLiangDream** [comment]
https://www.npmjs.com/package/mp-colorui
![image](https://user-images.githubusercontent.com/24502330/65669190-aecd5b00-e075-11e9-86c8-62fc37fd90d8.png)
可以试着手动将版本号改为 0.5.0，在 npm install 一下
