### ISSUE TITLE
Select 组件 中 selector 的 value 不能动态设置

### ISSUE THREAD

**Issue by Jetereting** [yinLiangDream/mp-colorui#18]
用户进入的时候选择框 的位置是从后台获取的，
当后台获取到数据 setState 后，得到位置值，但这时候 Select 值没有变

```jsx
<ClSelect title='省份' mode='selector' selector={{ range: this.state.region, rangeKey: 'value', value: this.state.provinceI }} onChange={this.provinceChange.bind(this)} />
```

provinceI 为从后端获取的位置值

**Comment by Jetereting** [comment]
大佬这个计划啥时候修复？

**Comment by yinLiangDream** [comment]
@Jetereting 下个版本，大概国庆前一天

**Comment by Jetereting** [comment]
@yinLiangDream 收到

**Comment by Jetereting** [comment]
大佬 我来催更啦

**Comment by yinLiangDream** [comment]
下午下午，现在人在外面不方便😅




在2019年09月30日 09:11，Au 写道：

大佬 我来催更啦

**Comment by Jetereting** [comment]
好滴 大佬

**Comment by Jetereting** [comment]
还没没有完全好，现在 select 控件点进去弹出的列表位置是对的，但是 外层显示还是不对
![image](https://user-images.githubusercontent.com/11585188/65942985-0ba78780-e461-11e9-8ea8-1fe972cad651.png)

**Comment by yinLiangDream** [comment]
我再排查一下


在2019年10月01日 15:35，Au 写道：

还没没有完全好，现在 select 控件点进去弹出的列表位置是对的，但是 外层显示还是不对

**Comment by Jetereting** [comment]
加油 老大

**Comment by Jetereting** [comment]
啊啊啊啊 我的错，我没删好 dist ,删了重新运行可以啦，大佬国庆快乐

**Comment by Jetereting** [comment]
ClTabBar 的 active 不能动态设置
