### ISSUE TITLE
请问Swiper组件设置图片类型能自动播放滚动到下一张图片吗？

### ISSUE THREAD

**Issue by yinLiangDream** [yinLiangDream/mp-colorui#19]
请问Swiper组件设置图片类型能自动播放滚动到下一张图片吗？

_Originally posted by @lq2009v in https://github.com/yinLiangDream/mp-colorui/issues/5#issuecomment-535762881_

**Comment by Jetereting** [comment]
不是参数里能设置 interval 吗

**Comment by yinLiangDream** [comment]
@Jetereting 是有interval，尴尬的是，自动播放的入口我忘了加上了，所以默认是 false，就算设置了interval也没有效果……
