### ISSUE TITLE
ClAvatar 组件，真机中url 地址为本地图片 显示为全黑

### ISSUE THREAD

**Issue by Jetereting** [yinLiangDream/mp-colorui#20]
```tsx
        <View className='LoginButton'>
          <ClAvatar headerArray={[{ url: !constant.getAvatar() ? iconImg : constant.getAvatar() }, { url: iconImg }]} shape='round' size='xlarge' shadow />
          <Image src={iconImg} />
        </View>
```
iconImg 为本地图片
Image 标签为对照组

开发工具效果：
![image](https://user-images.githubusercontent.com/11585188/65758777-3b4a4d00-e14c-11e9-8afe-5768cae0d77e.png)

真机效果：
![image](https://user-images.githubusercontent.com/11585188/65760157-055a9800-e14f-11e9-81c2-877378288063.png)

**Comment by Jetereting** [comment]
当url 为网络地址的时候 都没有问题

**Comment by yinLiangDream** [comment]
是这样的，我使用的是 css 的 background 设置的，微信文档里也有说明，设置 background-image 只支持网络链接和 base64

**Comment by yinLiangDream** [comment]
我下个版本加个本地图片自动转 base64 ，这样就可以显示出来了
