### ISSUE TITLE
请问我参考demo使用Tabs组件在点击其中一个tab,在微信开发者工具上报如下错误是什么原因呢？

### ISSUE THREAD

**Issue by lq2009v** [yinLiangDream/mp-colorui#21]
![image](https://user-images.githubusercontent.com/26498222/65810873-fd4c3800-e1e2-11e9-9c6b-01be2ff1ced8.png)

**Comment by yinLiangDream** [comment]
@lq2009v  方便把这块代码发出来看一下吗

**Comment by gendseo** [comment]
@lq2009v 

如果使用了ES7语法，请在微信开发者工具中开启"增强编译"

参考 https://github.com/EastWorld/wechat-app-mall#%E7%BC%96%E8%AF%91%E8%AF%B4%E6%98%8E

**Comment by yinLiangDream** [comment]
安装一下这个 @tarojs/async-await 这是 Taro 的异步依赖，具体看这里 https://nervjs.github.io/taro/docs/async-await.html#docsNav
