### ISSUE TITLE
有的组件我想通过 js 调用，可以实现吗？

### ISSUE THREAD

**Issue by Jetereting** [yinLiangDream/mp-colorui#22]
比如 ClModal 我想做个通用登录模态框，然后各个页面可以通过 js 调用实现，就像 Taro.showModal 一样，请问可以实现吗？

**Comment by yinLiangDream** [comment]
这个微信小程序实现不了，因为微信小程序没有根页面，也不可以动态添加节点
-----------------------------------
不过可以曲线救国，你先写一个组件，然后在 app.js 里面配置 usingComponents 注册该组件，需要用到的页面直接写标签无需二次引入，同时使用全局变量来控制该组件就可以了
