### ISSUE TITLE
input 希望支持auto-focus 

### ISSUE THREAD

**Issue by secreter** [yinLiangDream/mp-colorui#23]
为了更好的定位以及解决问题，在提交 ISSUE 时，我希望你

1. 标明 `mp-colorui` 的版本号
2. 标明 `Taro` 的版本号
3. 贴出关于这次问题的相关代码或截图

input 希望支持auto-focus ,还有就是组件希望支持自定义class

**Comment by yinLiangDream** [comment]
这两个特性我会尽快加上
