### ISSUE TITLE
ClMessage :regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by Jetereting** [yinLiangDream/mp-colorui#25]
为了更好的定位以及解决问题，在提交 ISSUE 时，我希望你

1. 标明 `mp-colorui` 的版本号
`0.5.6`
2. 标明 `Taro` 的版本号
`1.3.20`
3. 贴出关于这次问题的相关代码或截图
```tsx
        <ClMessage
          message={'监测到视频地址，已成功复制'}
          show={this.state.messageShow}
          type={'success'}
        />
```
![image](https://user-images.githubusercontent.com/11585188/67263986-5a829300-f4dc-11e9-90c7-5e1b020d4719.png)

**Comment by yinLiangDream** [comment]
安装一下这个 @tarojs/async-await 这是 Taro 的异步依赖，具体看这里 https://nervjs.github.io/taro/docs/async-await.html#docsNav

**Comment by Jetereting** [comment]
生效！ 感谢大佬
