### ISSUE TITLE
ClShopBar 空间的 tabs 能否再加个 openType 参数

### ISSUE THREAD

**Issue by Jetereting** [yinLiangDream/mp-colorui#27]
![image](https://user-images.githubusercontent.com/11585188/67273671-7fcdcc00-f4f1-11e9-87c9-8cf8cf9c61fe.png)

比如我先点第一个分享按钮，就能做到分享，而在方法里又没法调起分享，所以能不能加个 openType 参数

**Comment by yinLiangDream** [comment]
理论上来说，只有 button 才有 openType 参数，也只有 button 才能唤起 openType，我这边改造一下吧

**Comment by yinLiangDream** [comment]
新版本已添加了 openType

**Comment by Jetereting** [comment]
收到 谢谢大佬，已应用到项目中了
