### ISSUE TITLE
Flex 布局 参数 align 没有 stretch

### ISSUE THREAD

**Issue by Jetereting** [yinLiangDream/mp-colorui#28]
![image](https://user-images.githubusercontent.com/11585188/67389498-508c8d00-f5cd-11e9-8483-1aa48ef0ef52.png)
比如 设定 align= stretch 后 使左右两边就等高了

**Comment by yinLiangDream** [comment]
emmm，今天修改的时候发现，属性我是写好的，如果传入 stretch 就会生效，文档和类型提示漏掉了……

**Comment by Jetereting** [comment]
嘻嘻
