### ISSUE TITLE
请教 ClTabBar 的正确使用方式

### ISSUE THREAD

**Issue by Jetereting** [yinLiangDream/mp-colorui#29]
我在主页底部放了 一个 ClTabBar 内含三个按钮，
默认第一个按钮是选中也就是当前页，
点击第二个按钮到 第二页，同时第二页底部也有同样的 ClTabBar，这页的 ClTabBar 第二个按钮为选中状态

但是这样做 在切页的时候 能明显的感觉到 页面的消失/出现

难道是 不跳转页面，都做在一个页面的 然后通过点击 ClTabBar 里的按钮 设置上面的哪些视图呈现，哪些视图隐藏

还是有其他更优雅的办法

**Comment by yinLiangDream** [comment]
小程序跳转页面必定会有一个跳转过程，实际上就是不切换页面，是写在一个页面内部，通过 tab 的激活不同的组件的显示/隐藏，这需要你合理的搭配，分模块引入

**Comment by Jetereting** [comment]
![image](https://user-images.githubusercontent.com/11585188/67465879-a407e500-f678-11e9-987f-041711d328b2.png)
果然这样写起来 也没想象中那么难受
