### ISSUE TITLE
ntrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.

### ISSUE THREAD

**Issue by robin-ming** [yinLiangDream/mp-colorui#3]
asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
 

H5 启动warning  在哪里修改

**Comment by yinLiangDream** [comment]
@robin-ming 
在 prod 文件下添加这一句 
<img width="303" alt="image" src="https://user-images.githubusercontent.com/24502330/61990003-bdde5f80-b06a-11e9-9ffe-8b50fd4c4092.png">

```js
webpackChain (chain) {
  chain.performance.set('hints', false);
}
```

<img width="671" alt="image" src="https://user-images.githubusercontent.com/24502330/61990026-0bf36300-b06b-11e9-8ea8-c71cd1bbf583.png">

**Comment by robin-ming** [comment]
好的  试了下 可以  谢啦
 


 




------------------ 原始邮件 ------------------
发件人: "梁音"<notifications@github.com>;
发送时间: 2019年7月27日(星期六) 中午12:36
收件人: "yinLiangDream/mp-colorui"<mp-colorui@noreply.github.com>;
抄送: "Ice✨"<839786983@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [yinLiangDream/mp-colorui] ntrypoint size limit: The followingentrypoint(s) combined asset size exceeds the recommended limit (244 KiB).This can impact web performance. (#3)




@robin-ming
 在 prod 文件下添加这一句
 
 webpackChain (chain) {   chain.performance.set('hints', false); }
