### ISSUE TITLE
ClFloatButton 真机中无法在 Video 之上

### ISSUE THREAD

**Issue by Jetereting** [yinLiangDream/mp-colorui#31]
![image](https://user-images.githubusercontent.com/11585188/67621579-20e6ba80-f843-11e9-80d0-4bb5a86a367c.png)
模拟器中可以，真机上不行

**Comment by yinLiangDream** [comment]
原生组件的层级永远大于自定义组件
微信文档 https://developers.weixin.qq.com/miniprogram/dev/component/native-component.html
