### ISSUE TITLE
swiper组件在h5中阻挡跳转,type=card滑动会浏览器崩溃

### ISSUE THREAD

**Issue by vand7813** [yinLiangDream/mp-colorui#38]
"mp-colorui": "^0.5.10",
"@tarojs/taro": "1.3.25",

在h5开发模式下,
![image](https://user-images.githubusercontent.com/16217900/69606897-029cf600-105f-11ea-91b8-df79ba270178.png)

滑动会造成浏览器卡顿崩溃,
不设置autoplay,circular可以正常显示.但是 Taro.navigateTo({url:"/pages/play/play"}) 失效

![image](https://s2.ax1x.com/2019/11/26/MzcIM9.gif)

**Comment by yinLiangDream** [comment]
我排查一下，这几天会有新版本发布，会修复这个问题
