### ISSUE TITLE
按需加载样式 不能展示全面。复杂的组件 按需使用样式错乱，打开全局没有问题

### ISSUE THREAD

**Issue by wjm0913** [yinLiangDream/mp-colorui#41]
为了更好的定位以及解决问题，在提交 ISSUE 时，我希望你

1. 标明 `mp-colorui` 的版本号
2. 标明 `Taro` 的版本号
3. 贴出关于这次问题的相关代码或截图

**Comment by yinLiangDream** [comment]
请问是怎么引入文件的

**Comment by wjm0913** [comment]
![e22078148091261291ebd91ef93f97f8](https://user-images.githubusercontent.com/45306520/70517836-3c4c2180-1b74-11ea-9439-a0697020d736.jpg)

**Comment by wjm0913** [comment]
![7222188b6872de195ead1c88dca2cb2d](https://user-images.githubusercontent.com/45306520/70517868-49691080-1b74-11ea-93ce-65e469002780.jpg)

**Comment by wjm0913** [comment]
![b06705130dd59d7050206d8661aa4c29](https://user-images.githubusercontent.com/45306520/70517874-4cfc9780-1b74-11ea-8ce5-b8b592e5ad47.jpg)

**Comment by yinLiangDream** [comment]
这是因为没有获取到 baseCSS.scss 的内容导致了一些基础样式缺失，有两个方案可以选择
- 按照我文档写的[内容](https://yinliangdream.github.io/mp-colorui-doc/home/quick.html#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8)，将所有按需加载的样式放入 app.scss 中，组件打开 addGlobalClass 属性即可
- 在每个需要的组件里的 index.scss 都引入 baseCSS.scss 文件，但是这样会导致文件打包很大，这就是我不推荐的原因，会增大文件打包体积

**Comment by wjm0913** [comment]
<img width="1042" alt="1575973294720_BFC59064-37D5-4D25-B840-8F3E006BFDC4" src="https://user-images.githubusercontent.com/45306520/70521512-52f57700-1b7a-11ea-8bc2-f00157d3147b.png">

**Comment by wjm0913** [comment]
<img width="989" alt="1575973322767_0B99BCB7-2B84-4C79-87C2-A0CBCC0497FB" src="https://user-images.githubusercontent.com/45306520/70521529-57219480-1b7a-11ea-9688-17ff8dbc5210.png">

**Comment by wjm0913** [comment]
是这样吗！还是这样的问题！ 是我哪里做的不对吗！谢谢

**Comment by yinLiangDream** [comment]
需要在app. scss引入baseCSS. scss




在2019年12月10日 18:25，wjm0913 写道：

是这样吗！还是这样的问题！ 是我哪里做的不对吗！谢谢

**Comment by yinLiangDream** [comment]
这是我的问题，文档里没有说明，我下个版本会修复这个问题，届时就不需要引入 baseCSS 这个文件了

**Comment by wjm0913** [comment]
感谢回复。做的真好。大部分功能 都有了。感谢 作者开源！

**Comment by wjm0913** [comment]
> 这是我的问题，文档里没有说明，我下个版本会修复这个问题，届时就不需要引入 baseCSS 这个文件了

您好  还是没有引入成功baseCSS文件

**Comment by wjm0913** [comment]
> 这是我的问题，文档里没有说明，我下个版本会修复这个问题，届时就不需要引入 baseCSS 这个文件了
引入成功了，刚才没有 刷新。感谢
