### ISSUE TITLE
ClRadio  这个是你们遍历的问题吧  

### ISSUE THREAD

**Issue by HelloSuLei** [yinLiangDream/mp-colorui#43]
![1576115274(1)](https://user-images.githubusercontent.com/40617082/70675628-a2e05500-1cc4-11ea-8b20-9cac80af00a0.jpg)
![1576115300(1)](https://user-images.githubusercontent.com/40617082/70675632-a5db4580-1cc4-11ea-8c09-317986f73ca3.jpg)

"mp-colorui": "^0.6.0",

**Comment by yinLiangDream** [comment]
循环的 key 是根据 value 值确定的，value 值是 1，2 是不合法的 key 值，目前解决方法为将 value 不能为纯数字

**Comment by yinLiangDream** [comment]
下个版本修复这个问题

**Comment by HelloSuLei** [comment]
![1576128962(1)](https://user-images.githubusercontent.com/40617082/70685455-72101800-1ce4-11ea-8189-53990e77e5c4.jpg)
![1576115300(1)](https://user-images.githubusercontent.com/40617082/70685462-76d4cc00-1ce4-11ea-8805-840fc735ef9e.jpg)

**Comment by HelloSuLei** [comment]
这怎么写才不会报错警告

**Comment by yinLiangDream** [comment]
我这边没有复现问题，请问你的 Taro 版本是什么

**Comment by yinLiangDream** [comment]
<img width="378" alt="图片" src="https://user-images.githubusercontent.com/24502330/70687728-f36aa900-1cea-11ea-8051-4c8364b2d984.png">
<img width="410" alt="图片" src="https://user-images.githubusercontent.com/24502330/70687742-fb2a4d80-1cea-11ea-90c3-681cfb65a303.png">
<img width="879" alt="图片" src="https://user-images.githubusercontent.com/24502330/70687761-02515b80-1ceb-11ea-9b71-6bc63ff8b2ba.png">

**Comment by HelloSuLei** [comment]
![Uploading 1576132630(1).jpg…]()

**Comment by yinLiangDream** [comment]
升级到 0.6.2 版本看看
