### ISSUE TITLE
card组件有没有单击事件啊

### ISSUE THREAD

**Issue by muzi16218** [yinLiangDream/mp-colorui#44]
为了更好的定位以及解决问题，在提交 ISSUE 时，我希望你

1. 标明 `mp-colorui` 的版本号
2. 标明 `Taro` 的版本号
3. 贴出关于这次问题的相关代码或截图

**Comment by yinLiangDream** [comment]
你可以在 Card 组件外套一层 原生View，在 View 上添加单击事件
