### ISSUE TITLE
这个怎么重置默认城市

### ISSUE THREAD

**Issue by HelloSuLei** [yinLiangDream/mp-colorui#46]
![微信截图_20191216094328](https://user-images.githubusercontent.com/40617082/70873401-ae938a80-1fe8-11ea-98ca-3157bf57cc18.png)

**Comment by PlutoCA** [comment]
我也碰到这问题，在state设置了一个place初始值，然后想更改，
```javascript
 <ClSelect
  onChange={this.changeRegion}
  className="region_select"
  mode="region"
  title="选择城市"
  region={{ value: place }}
/>
```
setState 设置无效 监听这个place值已经更改了，页面上的选中值改不了
@yinLiangDream

**Comment by yinLiangDream** [comment]
@HelloSuLei @PlutoCA  我检查了一下，是代码问题，下个版本修复哈

**Comment by PlutoCA** [comment]
好的

> @HelloSuLei @PlutoCA 我检查了一下，是代码问题，下个版本修复哈

👌
