### ISSUE TITLE
ClInput里的button会缩在一起

### ISSUE THREAD

**Issue by xuwenyan** [yinLiangDream/mp-colorui#47]
为了更好的定位以及解决问题，在提交 ISSUE 时，我希望你

1. 标明 `mp-colorui` 的版本号 0.6.2
2. 标明 `Taro` 的版本号 1.3.29
3. 贴出关于这次问题的相关代码或截图

ClInput里的button会缩在一起，比如“获取”的button，会变成两行，demo里也是这样的

**Comment by yinLiangDream** [comment]
下个版本修复这个问题

**Comment by xuwenyan** [comment]
看到了，新版已修改，谢谢
