### ISSUE TITLE
ClLayout怎么没有bottom属性

### ISSUE THREAD

**Issue by xuwenyan** [yinLiangDream/mp-colorui#48]
ClLayout怎么没有bottom属性
比如有个按钮是靠底部的布局，要怎么实现

为了更好的定位以及解决问题，在提交 ISSUE 时，我希望你

1. 标明 `mp-colorui` 的版本号0.6.2
2. 标明 `Taro` 的版本号
3. 贴出关于这次问题的相关代码或截图

**Comment by yinLiangDream** [comment]
ClLayout 就是一个盒子，你可以设置内边距和外边距，无法做到定位某个元素的位置。

如果想有个按钮靠底部方案有很多种，比如绝对定位，固定定位之类
