### ISSUE TITLE
为什么很多does not look like a valid key name的错误？

### ISSUE THREAD

**Issue by birdycn** [yinLiangDream/mp-colorui#50]
我看了下错误都是mp-colorui组件包出来的，例如：
 wx:key="$original.cu_avatar_id" does not look like a valid key name (did you mean wx:key="cu_avatar_id" ?)

**Comment by yinLiangDream** [comment]
下个版本修复这个问题，麻烦提供一下相关代码或截图，我这边可以排查一下
