### ISSUE TITLE
全局样式.scrollx view没有存在的必要吧！

### ISSUE THREAD

**Issue by birdycn** [yinLiangDream/mp-colorui#51]
引用tabs后会导致原有的样式出错，调试了一下发现是
.scrollx view, .scrollx div {
./npm/mp-colorui/dist/weapp/components/tabs/index.wxss: 5width: 100%;
height: 100rpx;
display: inline-block;
}

引起的。。实在是无法理解，这个东西存在的必要是什么？小程序如何覆盖全局样式

**Comment by yinLiangDream** [comment]
手误少写了一个符号。。。下个版本修复这个问题……
