### ISSUE TITLE
图片不加载

### ISSUE THREAD

**Issue by MyJimmyZhou** [yinLiangDream/mp-colorui#52]
为了更好的定位以及解决问题，在提交 ISSUE 时，我希望你

1.  `mp-colorui`  版本 0.6.3
2. `Taro`  版本 2.0.0
3. 代码
`       <ClSwiper
          type='screen'
          list={[{ url: 'http://bpic.ooopic.com/16/03/72/16037202-17ea8e164c9416d560d3f69522d7db25-3.jpg' }, { url: 'http://bpic.ooopic.com/17/82/09/17820965-6d9a7734adf87ed72a61ba993ebd144b-3.jpg' }]}
          circular='true'
          dot='round'
          indicatorDots='true'
          indicatorColor='#8799a3'
          indicatorActiveColor='#0081ff'
          autoplay='true'
        />`
结果：
只有点点，没有图

**Comment by yinLiangDream** [comment]
<img width="908" alt="图片" src="https://user-images.githubusercontent.com/24502330/71227459-4ad7cd00-231a-11ea-88a6-05af915c0fe3.png">
这个图加载不出来啊

**Comment by MyJimmyZhou** [comment]
编译后小程序上没有相关元素。求助

**Comment by MyJimmyZhou** [comment]
![image](https://user-images.githubusercontent.com/13486578/71229982-b58d0680-2322-11ea-8113-34ed994bb9c9.png)
![image](https://user-images.githubusercontent.com/13486578/71229988-bde54180-2322-11ea-8ee4-062b102b2f11.png)

**Comment by yinLiangDream** [comment]
元素就在 #shadow-root 下面

**Comment by yinLiangDream** [comment]
另外，如果图片确实存在，且能加载但是没出现图片，请在开发者工具把下面这个选项打开
<img width="428" alt="图片" src="https://user-images.githubusercontent.com/24502330/71231317-57fbb880-2328-11ea-9a7e-66911fc079b9.png">

**Comment by MyJimmyZhou** [comment]
![image](https://user-images.githubusercontent.com/13486578/71236194-4e2e8100-2339-11ea-8e4e-a0a1a8e35a70.png)
Network 也没有加载图片的请求

**Comment by yinLiangDream** [comment]
发现原因了……我代码问题，没有给 type 设置默认值，你手动加一个 type: 'image'就行了
<img width="675" alt="图片" src="https://user-images.githubusercontent.com/24502330/71236591-4e7b4c00-233a-11ea-8628-74af78e0cf86.png">
