### ISSUE TITLE
作者你好，在使用Tabs标签页时报错，麻烦看一下，版本0.6.3

### ISSUE THREAD

**Issue by jack12345666** [yinLiangDream/mp-colorui#54]
![J V)JW{9P%XQ5PYMY N@RS3](https://user-images.githubusercontent.com/35050738/71225917-0695fe00-2315-11ea-9cf0-a89485ad9f38.png)

**Comment by yinLiangDream** [comment]
请问安装了 @tarojs/async-await 这个包了吗

**Comment by jack12345666** [comment]
没有，我现在装上去试试

**Comment by jack12345666** [comment]
这个需要在页面引用吗？

**Comment by yinLiangDream** [comment]
在 app.js 中引用
<img width="471" alt="图片" src="https://user-images.githubusercontent.com/24502330/71228005-e87fcc00-231b-11ea-8d38-3c053db69f3d.png">

**Comment by jack12345666** [comment]
好的，谢谢大佬

**Comment by jack12345666** [comment]
![image](https://user-images.githubusercontent.com/35050738/71228345-d6eaf400-231c-11ea-8ba7-d1fa5c3ef884.png)
报了这个错误

**Comment by yinLiangDream** [comment]
请问是浏览器环境吗

**Comment by yinLiangDream** [comment]
id 不要为纯数字

**Comment by jack12345666** [comment]
我的id是纯数字，好了，谢谢作者
