### ISSUE TITLE
[Bug] Input autocomplete mode, click complete item not trigger onChange event

### ISSUE THREAD

**Issue by CodingPapi** [yinLiangDream/mp-colorui#56]
1. `mp-colorui` 的版本号----> 0.6.3
2. `Taro` 的版本号------------>1.3.26

Input在autocomplete模式下，点击自动补全的item之后，不会出发onChange事件。此时如何获取Input控件中的值？

**Comment by yinLiangDream** [comment]
下个版本会新增一个点击补全项触发的函数
