### ISSUE TITLE
城市选择能默认value吗

### ISSUE THREAD

**Issue by HelloSuLei** [yinLiangDream/mp-colorui#57]
![image](https://user-images.githubusercontent.com/40617082/71506669-dc1be600-28bc-11ea-915c-7058a6fa3bb3.png)

**Comment by yinLiangDream** [comment]
可以的啊，看文档[说明](https://yinliangdream.github.io/mp-colorui-doc/form/select.html#%E5%8F%82%E6%95%B0%E8%AF%B4%E6%98%8E)，看 region 设置，具体地区和 code 设置可以看[这里](https://yinliangdream.github.io/area/)

**Comment by mouyong** [comment]
能通过 "河北省,石家庄市,长安区" 这样的方式来设置默认地址吗
