### ISSUE TITLE
mp-colorui 0.6.4 使用ClSearchBar 时无法控制focus

### ISSUE THREAD

**Issue by gegeliu** [yinLiangDream/mp-colorui#58]
.能够添加 SearchBar 属性控制Input focus
  这可能需要 添加 Input 的 ref 定义，具体可以参见

   https://stackoverflow.com/questions/28889826/set-focus-on-input-after-render
  希望新版能够支持，多谢！

**Comment by yinLiangDream** [comment]
是想要 autoFocus 的功能吗
