### ISSUE TITLE
小程序 引用 ClUtils 就会出现编译出错

### ISSUE THREAD

**Issue by Zigei** [yinLiangDream/mp-colorui#64]
很奇葩的报错 为什么引用 utils 会导致 Taro defined

![image](https://user-images.githubusercontent.com/25807986/72230982-cc5a0c80-35f3-11ea-8dfc-df0da5da1766.png)

还有 部分 类型提示不是很友好

util 里面你提供了 rule 的方法但是 提示却是

rule ?:{
 email?:()=>void
}
倒是直接使用时 会导致编辑器报错  要我 utils && uils.rule &&...  有点难受

还有 一些 list  直接提供了 list 的类型 没有提供 item 的类型 
导致不能继承 item 在上面附加一些自己的东西

Taro 2.0.0
mp-colorui  0.6.5

**Comment by yinLiangDream** [comment]
我去排查一下

**Comment by yinLiangDream** [comment]
真是奇葩的报错……我发现只有组件不会报错，通过 ui 命令打包出来的工具引入都会报错，貌似 Taro 将引入的工具当做组件来处理了

**Comment by yinLiangDream** [comment]
下个版本我会更新一下 ClUtils 的引入方式，就没有这种问题了
