### ISSUE TITLE
components/tabBar组件中，使用图片img属性，未显示。看源码，并没有写img的相关dom结构

### ISSUE THREAD

**Issue by yarkone** [yinLiangDream/mp-colorui#67]
1."mp-colorui": "^0.6.7",
2. "@tarojs/components": "2.0.2",
3. 我的代码：
![image](https://user-images.githubusercontent.com/22462736/73897914-8f1b2e80-48c2-11ea-948b-37289b4e0531.png)
我的代码展现：
![image](https://user-images.githubusercontent.com/22462736/73897899-7f034f00-48c2-11ea-9684-0ab2d3c6c112.png)
官网组件源码：
![image](https://user-images.githubusercontent.com/22462736/73897938-a5c18580-48c2-11ea-8384-f1b4579635c8.png)

**Comment by yinLiangDream** [comment]
前些日子有些忙，这两天我会修复这个问题
