### ISSUE TITLE
clinput  type = digit 在小程序中 没有弹出 对应的键盘

### ISSUE THREAD

**Issue by Zigei** [yinLiangDream/mp-colorui#68]
clinput  type = digit 在小程序中 没有弹出 对应的键盘

在小程序中弹出的是默认键盘  不是小程序的 digit 的键盘

1. 标明 `mp-colorui` 的版本号     0.6.7
2. 标明 `Taro` 的版本号     2.0.3

**Comment by yinLiangDream** [comment]
是默认键盘，但是应该做了输入限制
