### ISSUE TITLE
ClScreenDrawer 

### ISSUE THREAD

**Issue by guanrongjia** [yinLiangDream/mp-colorui#69]
为了更好的定位以及解决问题，在提交 ISSUE 时，我希望你

1.  "mp-colorui": "^0.6.7",
2. "@tarojs/taro": "1.3.31",
3. ClScreenDrawer丢失返回箭头
![image](https://user-images.githubusercontent.com/31066159/74601291-818e5180-50d7-11ea-94c0-521f5687ac93.png)

**Comment by yinLiangDream** [comment]
是必现吗？

**Comment by guanrongjia** [comment]
必现的呀。
我最后没用这个组件了，
你们示例中那个白色的返回箭头没有渲染出来，
我审查元素也没看见。
但是点击mask区域，是可以收起来的

**Comment by yinLiangDream** [comment]
我突然明白了……是你下面的导航栏把这个小图标给遮住了……

**Comment by guanrongjia** [comment]
问题是导航栏也是用的mp-colorui的组件啊。
这个属于冲突还是怎么说，反正最好处理下吧

**Comment by yinLiangDream** [comment]
两种方案
1. 不要将导航栏设置为 fix 模式，这样就会跟随 Drawer 联动，当然如何将导航栏置底，可以用 flex 布局
2. 点击的时候手动将导航栏隐藏，还原的时候再恢复

**Comment by guanrongjia** [comment]
好的，nice，多谢你了
