### ISSUE TITLE
ClSelect is hard to trigger click action

### ISSUE THREAD

**Issue by CodingPapi** [yinLiangDream/mp-colorui#73]
mp-colorui:  0.6.10
taro: 2.0.5

Unlike Picker in taro, ClSelect is very hard to click and trigger the popup window. I can only click the area of showing current selected value on the right, and it is a small trigger area.
Picker in taro can trigger select action by touching anywhere of the Picker component.

**Comment by yinLiangDream** [comment]
I will fix this problem
