### ISSUE TITLE
taro3.0提示resolve './style/index.scss'

### ISSUE THREAD

**Issue by birdycn** [yinLiangDream/mp-colorui#75]
taro3.0提示resolve './style/index.scss'，是不是应该发布新版本了

**Comment by yinLiangDream** [comment]
五一会进行更新，最近有点忙，谅解一下…

**Comment by XieShangZheng** [comment]
> 五一会进行更新，最近有点忙，谅解一下…

请问大佬什么时候准备支持 taro3 呀

**Comment by yinLiangDream** [comment]
> > 五一会进行更新，最近有点忙，谅解一下…
> 
> 
> 
> 请问大佬什么时候准备支持 taro3 呀

真的是太忙了最近，我这周末看看，别急别急…

**Comment by guanrongjia** [comment]
大佬，还不支持 taro3 吗。。。
急用

**Comment by guanrongjia** [comment]
> > > 五一会进行更新，最近有点忙，谅解一下…
> > 
> > 
> > 请问大佬什么时候准备支持 taro3 呀
> 
> 真的是太忙了最近，我这周末看看，别急别急…

大佬，现在可以支持 taro3 了嘛。我 6 月 11 号尝试，还不可以

**Comment by yinLiangDream** [comment]
> > > > 五一会进行更新，最近有点忙，谅解一下…
> 
> > > 
> 
> > > 
> 
> > > 请问大佬什么时候准备支持 taro3 呀
> 
> > 
> 
> > 真的是太忙了最近，我这周末看看，别急别急…
> 
> 
> 
> 大佬，现在可以支持 taro3 了嘛。我 6 月 11 号尝试，还不可以

可以看看文档里的开发计划哈，有一整年的迭代计划

**Comment by HazySoda** [comment]
大佬，看计划最近适配 Taro 3 的版本要上了吗？

**Comment by Minfee** [comment]
大佬现在准备开发taro应用，想用这套UI请问下有没有大致支持3的时间呐，如果很快的话就再等等。

**Comment by yinLiangDream** [comment]
> 大佬现在准备开发taro应用，想用这套UI请问下有没有大致支持3的时间呐，如果很快的话就再等等。

哎，难受，其实代码已经开发完了，但是 Taro 那边的问题，就算我发布了也用不来，自己测试下来渲染不正常，https://github.com/NervJS/taro/issues/7098，等新版本发布后我看看

**Comment by Leadrive** [comment]
期待，我也想把Taro-UI改成这个了。

**Comment by yinLiangDream** [comment]
3.x 支持了，1.0.0-alpha.0.0.1 版本发布了
