### ISSUE TITLE
点击搜索框清空icon，内容清空，但搜索的结果列表还没消失

### ISSUE THREAD

**Issue by Ardanas** [yinLiangDream/mp-colorui#77]
首页搜索框，搜索出结构后，点击搜索框清空icon，内容清空，但搜索的结果列表还没消失
![image](https://user-images.githubusercontent.com/30264837/80438899-dd772100-8937-11ea-8529-c8b01fe82a2a.png)

**Comment by yinLiangDream** [comment]
这个是我自己写的一个bug哈，五一期间我会更新新版本，届时这个问题我会去解决

**Comment by Ardanas** [comment]
nice bro!------------------ 原始邮件 ------------------
发件人: "梁音"<notifications@github.com>
发送时间: 2020年4月28日(星期二) 下午3:09
收件人: "yinLiangDream/mp-colorui"<mp-colorui@noreply.github.com>;
抄送: "Ardanas"<719481334@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [yinLiangDream/mp-colorui] 点击搜索框清空icon，内容清空，但搜索的结果列表还没消失 (#77)




 
这个是我自己写的一个bug&#x54C8;，五一期间我会更新新版本，届时这个问题我会去解决
 
&mdash;
