### ISSUE TITLE
关于ClTag 中 icon 使用问题

### ISSUE THREAD

**Issue by DWNEWS-mawenjie** [yinLiangDream/mp-colorui#78]
ClTag 中的tags 属性 icon 如何使用？
`const tags = [
  {
    color: 'red',
    plain: true,
    icon: 'appreciate'
  }, {
    text: '民主',
    color: 'brown',
    plain: true
  }
]`
`<ClTag tags={tags} shape="round" />`
使用 Icon-iconName 中icon name 无效果

**Comment by yinLiangDream** [comment]
请问是用的组件库内置的图标还是第三方引入的图标？

**Comment by DWNEWS-mawenjie** [comment]
组件库内的icon 
`const likeTag = [
  {
    color: 'greyLight',
    icon: 'emoji'
  }, {
    text: '0',
    color: 'greyLight'
  }
]`

**Comment by yinLiangDream** [comment]
已定位到当前问题，下个版本会修复~

**Comment by DWNEWS-mawenjie** [comment]
下个版本预计什么时候更新？

**Comment by yinLiangDream** [comment]
今天

**Comment by yinLiangDream** [comment]
版本已发

**Comment by LeeeMooo** [comment]
iconfont不支持吗

**Comment by yinLiangDream** [comment]
目前不支持，这也是我想3.0进行改造的地方




在2020年05月27日 19:39，LeeeMooo 写道：

iconfont不支持吗
