### ISSUE TITLE
weapp/style/index.scss 文件缺失

### ISSUE THREAD

**Issue by shangZhengXie** [yinLiangDream/mp-colorui#79]
为了更好的定位以及解决问题，在提交 ISSUE 时，我希望你

1. 标明 `mp-colorui` 的版本号
0.6.14
2. 标明 `Taro` 的版本号
Taro 3.0.0
3. 贴出关于这次问题的相关代码或截图
![报错截图](https://qn.xiesz.com/AT/061230.png?blog)

**Comment by yinLiangDream** [comment]
Taro3目前还不支持哈

**Comment by yinLiangDream** [comment]
3.x 支持了，1.0.0-alpha.0.0.1 版本发布了
