### ISSUE TITLE
关于按钮分享问题

### ISSUE THREAD

**Issue by DWNEWS-mawenjie** [yinLiangDream/mp-colorui#83]
`<ClButton>`标签中没有像`<Button>`标签中的 data-share 属性，获取不到分享的数据，是否可以加一个？
如：
`<Button openType='share' data-share={{ id: '12345' }} >分享</Button>`
或者使用` <ClButton> ` 标签怎么获取按键信息？

**Comment by yinLiangDream** [comment]
周末加

**Comment by DWNEWS-mawenjie** [comment]
好的🙏

**Comment by DWNEWS-mawenjie** [comment]
添加完 `customData` 后，还是没有分享按钮的相关数据
`<ClButton shadow={false} bgColor='white' openType='share' customData={{ article: '111111' }} ></ClButton>`
![image](https://user-images.githubusercontent.com/32052990/84611932-b5e11580-aef1-11ea-8c4a-4e1ec579aa66.png)

**Comment by yinLiangDream** [comment]
data-作为前缀

**Comment by DWNEWS-mawenjie** [comment]
`<ClButton shadow={false} bgColor='white' openType='share' customData={{ 'data-article': '111111' }} ></ClButton>`
这样吗？

**Comment by yinLiangDream** [comment]
> `<ClButton shadow={false} bgColor='white' openType='share' customData={{ 'data-article': '111111' }} ></ClButton>`
> 
> 这样吗？

是的，看看有效果没

**Comment by DWNEWS-mawenjie** [comment]
没有，还是一样
![image](https://user-images.githubusercontent.com/32052990/84614444-be891a00-aef8-11ea-9b8e-f6df43f49cd8.png)

**Comment by yinLiangDream** [comment]
> 没有，还是一样
> 
> ![image](https://user-images.githubusercontent.com/32052990/84614444-be891a00-aef8-11ea-9b8e-f6df43f49cd8.png)
> 
> 

请问直接用Taro 提供的 Button 有用吗

**Comment by DWNEWS-mawenjie** [comment]
taro 的有数据
`<Button openType='share' data-share={{ id: '11111' }} >分享</Button>`
![image](https://user-images.githubusercontent.com/32052990/84614824-d9a85980-aef9-11ea-8881-ce4ec12f605f.png)

**Comment by yinLiangDream** [comment]
> taro 的有数据
> 
> `<Button openType='share' data-share={{ id: '11111' }} >分享</Button>`
> 
> ![image](https://user-images.githubusercontent.com/32052990/84614824-d9a85980-aef9-11ea-8881-ce4ec12f605f.png)
> 
> 

我排查一下，稍等

**Comment by yinLiangDream** [comment]
升级到 0.6.16版本试试

**Comment by DWNEWS-mawenjie** [comment]
可以了，辛苦了，谢谢🙏
