### ISSUE TITLE
部分tsx文件没有编译成js

### ISSUE THREAD

**Issue by sooboy** [yinLiangDream/mp-colorui#87]
![image](https://user-images.githubusercontent.com/848440/88748076-ba504d80-d182-11ea-8a80-f64114376382.png)

为什么部分tsx文件没有编译成js啊

` "version": "0.6.16",`
👽 Taro v3.0.5  引用后会直接报错，应该是编译时忽略了node_modules里的文件

**Comment by yinLiangDream** [comment]
3.x 还没支持哈

**Comment by yinLiangDream** [comment]
3.x 支持了，1.0.0-alpha.0.0.1 版本发布了
