### ISSUE TITLE
建议单独发布一份适用于taro的css库

### ISSUE THREAD

**Issue by mrjasonjiang** [yinLiangDream/mp-colorui#89]
为了更好的定位以及解决问题，在提交 ISSUE 时，我希望你

1. 标明 `mp-colorui` 的版本号
2. 标明 `Taro` 的版本号
3. 贴出关于这次问题的相关代码或截图

**Comment by yinLiangDream** [comment]
是 Taro3 使用报错吗

**Comment by mrjasonjiang** [comment]
> 是 Taro3 使用报错吗

有其中原因吧。个人建议😁

**Comment by yinLiangDream** [comment]
> > 是 Taro3 使用报错吗
> 
> 有其中原因吧。个人建议😁

适配 Taro3 的版本发布了哦，1.0.0-alpha.0.0.1
