### ISSUE TITLE
Taro3.0.6使用ClCard报错

### ISSUE THREAD

**Issue by lzhlo** [yinLiangDream/mp-colorui#91]
### `mp-colorui`版本
> 1.0.0-alpha.0.0.1
### `taro`版本
> 3.0.5
### 代码
```
import React from 'react'
// eslint-disable-next-line import/first
import {View} from '@tarojs/components'
import TabBar from '../libraries/tab/tabBar';
// eslint-disable-next-line import/first
import {ClCard, ClDrawer} from 'mp-colorui'


export default function Index() {
  return (
    <View>
      <ClCard>
        我自带边距，你可以在里面填充任何自定义内容
      </ClCard>
    </View>
  )
}
```
### 报错内容
> `Cannot read property 'props' of undefined`

![O5GUY7ZN1$_S ZWMS ~ B](https://user-images.githubusercontent.com/26341286/89266214-3574a080-d668-11ea-9ec6-3fb89afa8def.png)

**Comment by liudonghua123** [comment]
我发现很多问题其实都是Taro升级了引起的，我改了一些代码，例如 https://github.com/yinLiangDream/mp-colorui/issues/102 https://github.com/yinLiangDream/mp-colorui/issues/98 等，我尝试改了一些代码后来才发现应该是Taro版本的问题，现在尝试按照 http://taro-docs.jd.com/taro/docs/migration/ https://www.cnblogs.com/o2team/p/13606772.html 来升级迁移一下看看

示例程序 https://github.com/yinLiangDream/mp-colorui-weapp/blob/b34224e1da47dcbb85ccf3ee79ead7cff8a1e677/package.json#L31-L40 之所以可能还可以正常使用是因为使用的Taro还是1.x的

**Comment by yinLiangDream** [comment]
Taro3请使用 1.0.0-beta.1 版本
