### ISSUE TITLE
floatButton编译报错

### ISSUE THREAD

**Issue by BryanBao** [yinLiangDream/mp-colorui#92]
为了更好的定位以及解决问题，在提交 ISSUE 时，我希望你

1. 标明 `mp-colorui` 的版本号
2. 标明 `Taro` 的版本号
3. 贴出关于这次问题的相关代码或截图

mp-colorui版本：0.6.17
Taro版本：2.2.11
问题截图：
![QQ图片20200806094753](https://user-images.githubusercontent.com/17572591/89481240-ec3c6200-d7c9-11ea-8b10-ff32a5d4f62c.png)

**Comment by yinLiangDream** [comment]
fix: 0.6.18
