### ISSUE TITLE
ClTip  自定义 小程序编译通过不了

### ISSUE THREAD

**Issue by giantss** [yinLiangDream/mp-colorui#93]
"@tarojs/taro": "2.2.13",
"mp-colorui": "^0.6.19",

![image](https://user-images.githubusercontent.com/13778798/91525398-f9192500-e933-11ea-9d4f-4437d7b0f73b.png)

**Comment by yinLiangDream** [comment]
其实只需要把renderClTip这个变量的内容塞到renderMessage就可以了，这是eslint的语法报错，不影响的
