### ISSUE TITLE
不能支持taro vue吗？

### ISSUE THREAD

**Issue by smarttang** [yinLiangDream/mp-colorui#96]
主要是，我这看到这个特别好，我在vue下发现不能用...

**Comment by liudonghua123** [comment]
这个可能需要用vue的方式封装一下，react、vue的ui库一般不是通用的

**Comment by yinLiangDream** [comment]
目前不支持VUE噢，使用Taro3.x请安装1.0.0-beta.1版本，使用Taro2.x请安装 0.6.18版本（后续不再维护）
